from __future__ import annotations

from typing import Dict

from .base import StrategyDefinition
from .ema_trend import DEFAULT_PARAMS as EMA_DEFAULT_PARAMS
from .ema_trend import EMA_STRATEGY, ema, slope_pct
from .atr_breakout import ATR_BREAKOUT_STRATEGY, DEFAULT_PARAMS as ATR_DEFAULT_PARAMS
from .bollinger_mean_reversion import (
    BOLLINGER_MEAN_REVERSION_STRATEGY,
    DEFAULT_PARAMS as BOLLINGER_DEFAULT_PARAMS,
)
from .donchian_trend import DONCHIAN_TREND_STRATEGY, DEFAULT_PARAMS as DONCHIAN_DEFAULT_PARAMS
from .funding_premium import FUNDING_PREMIUM_STRATEGY, DEFAULT_PARAMS as FUNDING_DEFAULT_PARAMS
from .rsi_mean_reversion import DEFAULT_PARAMS as RSI_DEFAULT_PARAMS, RSI_MEAN_REVERSION_STRATEGY
from .vortex_trend import DEFAULT_PARAMS as VORTEX_DEFAULT_PARAMS, VORTEX_TREND_STRATEGY


STRATEGY_REGISTRY: Dict[str, StrategyDefinition] = {
    EMA_STRATEGY.key: EMA_STRATEGY,
    ATR_BREAKOUT_STRATEGY.key: ATR_BREAKOUT_STRATEGY,
    DONCHIAN_TREND_STRATEGY.key: DONCHIAN_TREND_STRATEGY,
    RSI_MEAN_REVERSION_STRATEGY.key: RSI_MEAN_REVERSION_STRATEGY,
    VORTEX_TREND_STRATEGY.key: VORTEX_TREND_STRATEGY,
    BOLLINGER_MEAN_REVERSION_STRATEGY.key: BOLLINGER_MEAN_REVERSION_STRATEGY,
    FUNDING_PREMIUM_STRATEGY.key: FUNDING_PREMIUM_STRATEGY,
}
DEFAULT_STRATEGY_KEY = EMA_STRATEGY.key

__all__ = [
    "StrategyDefinition",
    "STRATEGY_REGISTRY",
    "DEFAULT_STRATEGY_KEY",
    "EMA_STRATEGY",
    "EMA_DEFAULT_PARAMS",
    "ATR_BREAKOUT_STRATEGY",
    "ATR_DEFAULT_PARAMS",
    "DONCHIAN_TREND_STRATEGY",
    "DONCHIAN_DEFAULT_PARAMS",
    "RSI_MEAN_REVERSION_STRATEGY",
    "RSI_DEFAULT_PARAMS",
    "VORTEX_TREND_STRATEGY",
    "VORTEX_DEFAULT_PARAMS",
    "BOLLINGER_MEAN_REVERSION_STRATEGY",
    "BOLLINGER_DEFAULT_PARAMS",
    "FUNDING_PREMIUM_STRATEGY",
    "FUNDING_DEFAULT_PARAMS",
    "ema",
    "slope_pct",
]
