model: gpt-5
temperature: null
reasoning_effort: null
verbosity: null
max_output_tokens: null
proposal_count: 8
tolerances:
  cagr: 0.08
  dd: 0.015
  sharpe: 0.2
stress:
  - return_scale: 0.9
    dd_scale: 1.05
    fee_scale: 2.0
  - return_scale: 0.8
    dd_scale: 1.5
    fee_scale: 1.0
  - return_scale: 0.85
    dd_scale: 1.2
    fee_scale: 1.2
